## Get the Data

In [31]:
from pathlib import Path
import pandas as pd
import zipfile
import urllib.request
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [32]:
def load_data():
    zip_path = Path("datasets/portugal_data.zip")
    if not zip_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url = "https://github.com/Mankz111/datasets/raw/main/portugal_data.zip"
        urllib.request.urlretrieve(url, zip_path)
    with zipfile.ZipFile(zip_path, 'r') as portugal_dataset:
        portugal_dataset.extractall(path="datasets")
    return pd.read_csv(Path("datasets/portugal_listinigs.csv"), low_memory = False)
                

In [33]:
data = load_data()
data.describe()

,Price,GrossArea,TotalArea,Parking,ConstructionYear,TotalRooms,NumberOfBedrooms,NumberOfWC,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
count,1.352360e+05,2.763800e+04,1.271530e+05,135342.000000,88021.000000,73244.000000,47041.000000,57256.000000,1.049520e+05,3.958300e+04,2.661700e+04,128700.000000
mean,3.681374e+05,2.789733e+03,5.140780e+05,0.549667,1989.303825,3.229357,2.665823,0.430785,1.403037e+03,5.636939e+04,3.086621e+03,1.544025
std,3.804044e+06,1.153670e+05,1.722937e+08,0.839257,26.684309,10.516977,1.790474,1.016360,3.474597e+04,5.208474e+06,1.185137e+05,1.764637
min,1.000000e+00,-7.000000e+00,-7.196067e+06,0.000000,1900.000000,0.000000,0.000000,-15.000000,0.000000e+00,0.000000e+00,-1.000000e+00,-13.000000
25%,8.400000e+04,1.000000e+02,9.100000e+01,0.000000,1973.000000,2.000000,2.000000,0.000000,8.000000e+01,2.580000e+02,1.045700e+02,0.000000
50%,2.100000e+05,1.640000e+02,1.590000e+02,0.000000,1994.000000,3.000000,3.000000,0.000000,1.180000e+02,6.790000e+02,1.680000e+02,1.000000
75%,3.950000e+05,2.940000e+02,5.000000e+02,1.000000,2009.000000,4.000000,3.000000,1.000000,2.040000e+02,2.890000e+03,3.000000e+02,2.000000
max,1.380000e+09,1.275000e+07,6.142007e+10,3.000000,2025.000000,2751.000000,21.000000,59.000000,5.429000e+06,9.923010e+08,1.275000e+07,131.000000


In [34]:
missing_percentage = (data.isnull().sum() / len(data)) * 100

In [35]:
missing_percentage

Price                     0.221343
District                  0.000000
City                      0.000000
Town                      0.001476
Type                      0.011805
EnergyCertificate         0.010329
GrossArea                79.608370
TotalArea                 6.185073
Parking                   0.143135
HasParking               49.670198
Floor                    79.393667
ConstructionYear         35.057107
EnergyEfficiencyLevel    50.353412
PublishDate              78.427134
Garage                   50.353412
Elevator                  0.023610
ElectricCarsCharging     50.353412
TotalRooms               45.959745
NumberOfBedrooms         65.292616
NumberOfWC               57.755873
ConservationStatus       85.766143
LivingArea               22.565223
LotSize                  70.795213
BuiltArea                80.361675
NumberOfBathrooms         5.043678
dtype: float64

In [36]:
cols_to_drop = ['GrossArea', 'Floor', 'PublishDate', 'ElectricCarsCharging', 'LotSize', 'BuiltArea', 'LivingArea', 'HasParking']

In [37]:
new_data = data.drop(cols_to_drop, axis=1)
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135536 entries, 0 to 135535
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Price                  135236 non-null  float64
 1   District               135536 non-null  object 
 2   City                   135536 non-null  object 
 3   Town                   135534 non-null  object 
 4   Type                   135520 non-null  object 
 5   EnergyCertificate      135522 non-null  object 
 6   TotalArea              127153 non-null  float64
 7   Parking                135342 non-null  float64
 8   ConstructionYear       88021 non-null   float64
 9   EnergyEfficiencyLevel  67289 non-null   object 
 10  Garage                 67289 non-null   object 
 11  Elevator               135504 non-null  object 
 12  TotalRooms             73244 non-null   float64
 13  NumberOfBedrooms       47041 non-null   float64
 14  NumberOfWC             57256 non-nul

In [38]:
missing_percentage = (new_data.isnull().sum() / len(new_data)) * 100

In [39]:
missing_percentage

Price                     0.221343
District                  0.000000
City                      0.000000
Town                      0.001476
Type                      0.011805
EnergyCertificate         0.010329
TotalArea                 6.185073
Parking                   0.143135
ConstructionYear         35.057107
EnergyEfficiencyLevel    50.353412
Garage                   50.353412
Elevator                  0.023610
TotalRooms               45.959745
NumberOfBedrooms         65.292616
NumberOfWC               57.755873
ConservationStatus       85.766143
NumberOfBathrooms         5.043678
dtype: float64

In [40]:
new_data["ConservationStatus"].value_counts()

ConservationStatus
New                 6688
Good condition      5269
Like new            2487
Used                2303
Needs renovation    1799
Reasonable           746
Name: count, dtype: int64

In [41]:
encoder = LabelEncoder()

In [42]:
data_conserv = new_data["ConservationStatus"]
data_conserv_encoded = encoder.fit_transform(data_conserv)

In [43]:
data_conserv_encoded

array([6, 6, 6, ..., 6, 6, 6], shape=(135536,))

In [44]:
print(encoder.classes_)

['Good condition' 'Like new' 'Needs renovation' 'New' 'Reasonable' 'Used'
 nan]


In [51]:
mapping_conserv = {
    "Good condition" : 4,
    "Like new": 5,
    'New' : 6,
    'Reasonable' : 3,
    'Used': 2,
    'Needs renovation': 1,
    np.nan: 0  
}

In [52]:
new_data["data_conserv_encoded"] = new_data["ConservationStatus"].map(mapping_conserv).fillna(0).astype(int)

In [54]:
new_data['EnergyEfficiencyLevel'].unique()

array([nan, 'F', 'NC', 'D', 'C', 'E', 'B-', 'B', 'A', 'A+', 'G',
       'No Certificate'], dtype=object)

In [55]:
mapping_EEL = {
    np.nan : 0,
    'No Certificate' : 0,
    'NC' : 0,
    'G' : 1, 
    'F' : 2,
    'D' : 3,
    'C' : 4,
    'E' : 5,
    'B-': 6,
    'B' : 7, 
    'A': 8, 
    'A+' : 9,  
}

In [65]:
data_eel = new_data["EnergyEfficiencyLevel"]
data_eel_encoder = encoder.fit_transform(data_eel)
data_eel_encoder

array([11, 11, 11, ...,  7,  9,  9], shape=(135536,))

In [66]:
new_data["data_eel_encoder"] = new_data["EnergyEfficiencyLevel"].map(mapping_EEL).fillna(0).astype(int)

In [67]:
new_data["EnergyEfficiencyLevel"].unique()

array([nan, 'F', 'NC', 'D', 'C', 'E', 'B-', 'B', 'A', 'A+', 'G',
       'No Certificate'], dtype=object)